# Generated by Django 3.2.6 on 2021-08-19 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210817_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='problem',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.category'),
        ),
    ]
