# Generated by Django 3.2.6 on 2021-08-20 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_likes_rating_ratingstar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='ads',
            new_name='posts',
        ),
    ]
