# Generated by Django 3.2.6 on 2021-08-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_ads_rating_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='liked_ads',
            new_name='liked_posts',
        ),
    ]
