# Generated by Django 3.2.6 on 2021-08-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ratingstar_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.IntegerField(default=0, verbose_name='value'),
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
